apiVersion: v1
kind: Secret
metadata:
  name: saj-secret
type: Opaque
data:
  SECRET: d015JCVLQXRNQUpkSEpaclNVbUNpV0txOWRuUDRmWGpmdFBGR01CI3lVWVVaSjluTGh4WWZVa3E3TWhqI2FjJkxDUFJxc242cEdGYzgleENyQGo=
  FIEF_CLIENT_SECRET: T0h0Sy11T1pCcmp3OW1IREFQd0hJX0NjaFhRT2RVU0lUZ0tTazdqUnNOYw==
  ENCRYPTION_KEY: X0VJNHVzOHUtTlJRVHBSSXJIck9BdGxVdXdoeEpteWRPQkNpbkhSWUVGbz0=
  FIEF_MAIN_USER_EMAIL: Ym9uZGkubHVjYUBnbWFpbC5jb20=
  FIEF_MAIN_USER_PASSWORD: ZTZLTFNVVnR4SDk4cyNoMA==
  DATABASE_USERNAME: ZmllZg==
  DATABASE_PASSWORD: cm1AR0NzKnZBN3M=
  DATABASE_NAME: ZmllZg==